[package]
name = "cellular_automata"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.9.1"
bevy_egui = "0.17.1"
bytemuck = "1.12.3"