[package]
name = "cellular_automata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# bevy = { git = "https://github.com/bevyengine/bevy" }
bevy = "0.10.0"
bevy_egui = "0.20.1"
bytemuck = "*"
rand = "*"
futures-lite = "1.12.0"

